apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-writer
spec:
  restartPolicy: Always
  containers:
    - name: writer
      image: cr.yandex/crp9ftr22d26age3hulg/yandex-cloud/csi-s3/csi-s3-driver:0.43.7
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "$(date -Iseconds) - written from csi-s3-writer" \
              >> /data/homework.txt
            sleep 30
          done
      volumeMounts:
        - name: s3-volume
          mountPath: /data
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: csi-s3-pvc
