apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  accessKeyID: "CHANGE_ME"
  secretAccessKey: "CHANGE_ME"
  endpoint: "https://storage.yandexcloud.net"
