apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  labels:
    app: nginx-distroless
spec:
  containers:
    - name: nginx
      image: kyos0109/nginx-distroless
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 128Mi