replicas: 1

nodeSelector:
  role: infra

tolerations:
  - key: dedicated
    operator: Equal
    value: infra
    effect: NoSchedule

persistence:
  enabled: false

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local
        isDefault: true
        editable: true